[package]
name = "noir_zkemail_benchmarks"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=0.35.0"

[dependencies]
zkemail = { tag = "v0.3.4", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
