[package]
name = "noir_zkemail_benchmarks"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=1.0.0"

[dependencies]
zkemail = { tag = "v0.4.1", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
